services:
  postgres_container:
    image: postgres:latest
    ports:
      - "5544:5432"  # Porta alterada para evitar conflito
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nimbledb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  


