server:
  servlet:
    context-path: /nimble-pagamento/api

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    nimble-pagamento: DEBUG

spring:
  profiles:
    active: ${APP_PROFILE:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5544/nimbledb}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    hikari:
      pool-name: SpringBootJPAHikariCP
      minimum-idle: 15
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000

# Configurações JWT para autenticação
security:
  token:
    jwt:
      expiration: ${JWT_EXPIRATION:7200} # Expiração do token em segundos
      secret: ${JWT_SECRET:f3a1c2d4e5b6a7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2} # Chave secreta para assinar o token

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect