server:
  servlet:
    context-path: /nimble-pagamento/api

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    nimble-pagamento: ${LOG_LEVEL:DEBUG}

spring:
  profiles:
    active: local #alterar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5544/nimbledb}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    hikari:
      pool-name: SpringBootJPAHikariCP
      minimum-idle: 15
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
